### ISSUE TITLE
Items not sorted (by publishing date)

### ISSUE THREAD

**Issue by manum45** [msasikanth/twine#427]
**Describe the bug**
Items are not sorted by publishing date.
It seems they are sorted by the time they were fetched by the client?

- When looking at a single feed, I see items from days ago at the top, with some newer ones towards the end. But I could not identify any order.
- When "All" feeds are selected, items are also not sorted by publishing date, leading to all items of one feed being shown, then the next and so on, instead of "interleaved"
- The "Today" view doesn't filter only items published today.
- The time shown next to each article also shows the time the feed was fetched, not the publishing date.

**Device Information**
 - Device:  Pixel 7
 - OS: Android 14
 - App Version 1.39.1 (302)

**Comment by msasikanth** [comment]
Interesting, we are using publish dates for sorting and order it as latest first. Can you provide the link to feed you are having this issue with? It's possible it might be a date parsing issue.

**Comment by vanniktech** [comment]
@msasikanth from my experience there are also RSS Feeds that do not provide a `pubDate` at all 🤓

From my code:

```
// We insert all items in reverse order and with each insert ask for the current time.
// This is so that sorting (pubDate, updated) by time works even when the feed gives us no date.
// One such feed: https://www.csa.fi.it/cgi-bin/rss_eventi.pl?ambito=FI
```

**Comment by msasikanth** [comment]
> @msasikanth from my experience there are also RSS Feeds that do not provide a `pubDate` at all 🤓
> 
> From my code:
> 
> ```
> // We insert all items in reverse order and with each insert ask for the current time.
> // This is so that sorting (pubDate, updated) by time works even when the feed gives us no date.
> // One such feed: https://www.csa.fi.it/cgi-bin/rss_eventi.pl?ambito=FI
> ```

Yeah, if there is no published date I fallback to current time when inserting.

**Comment by manum45** [comment]
It seems to affect a lot feeds for me, for example this one: https://www.rockpapershotgun.com/feed
From a quick look it appears to have publishing dates included.

**Comment by msasikanth** [comment]
> It seems to affect a lot feeds for me, for example this one: https://www.rockpapershotgun.com/feed
> 
> From a quick look it appears to have publishing dates included.

Can you share the screenshot of the issue, please?

**Comment by manum45** [comment]
![Screenshot](https://github.com/msasikanth/twine/assets/15382909/288be2ba-4470-48a3-82a2-55cc311c6581)

**Comment by msasikanth** [comment]
Thanks. This is definitely a date parsing issue, will resolve it next update.

**Comment by msasikanth** [comment]
@manum45 want to check if this is still an issue in the latest version of the app?

**Comment by manum45** [comment]
I'm on 1.43.0 and the issue still seems to be there. When I refresh all feeds it shows "0 min ago" for all articles.

23.05.2024 11:56:46 Sasikanth Miriyampalli ***@***.***>:

**Comment by vanniktech** [comment]
> Yeah, if there is no published date I fallback to current time when inserting.

Are you doing this every single time? I only do it the very first time.

**Comment by msasikanth** [comment]
> > Yeah, if there is no published date I fallback to current time when inserting.
> 
> Are you doing this every single time? I only do it the very first time.

Yeah, I decided to update the feed contents rather than ignore them if they already exist, since some sources make changes. But I guess it's not that common and can safely be ignored.

**Comment by rickdtc** [comment]
I'm sorry if I don't make sense, quite new to rss feeds, but can't the fallback be sorting it sequentially based on what comes first on the xml file?

**Comment by Gakai** [comment]
Hi, another feed with the same issue: https://feeds.transistor.fm/postgres-fm
For example the item "Intro to query optimization" from September '22 (and many other too) does indeed have a `pubDate`, but it still shows at the top with "0 min ago".

**Comment by vanniktech** [comment]
I also had this when I tried the app out to see how it's evolved. I added the Joe Rogan feed. It wasn't able to parse the dates and then everything was inserted reversed. So at the top was #1 instead of the latest one.

**Comment by msasikanth** [comment]
I will change the date parsing logic soon, hopefully that should resolve these issues. I already included tests for most common dates used in RSS feeds, but it looks like some of them are not getting properly parsed on Android.

**Comment by vanniktech** [comment]
You won't win this battle. I also still have some dates which I can't parse because they are simply wrong. Sometimes I get times like `13:00:60` (invalid seconds) or I get `Monday, 06/22/2024` (wrong date of week name). I have over 150 different date formattings in my tests and still some of them I can't parse.

**Comment by riumudutraz** [comment]
The problem for me seems to be that every time I open the app it seems to fetch every single article as new, so I have always the old articles on top (the ones from the first day of use) and it says that every article was fetched "0 minutes ago" ☹️

**Comment by rairmee** [comment]
Hello. It still shows the fetching date in 1.47.1
